### ISSUE TITLE
Define Product model

### ISSUE THREAD

**Issue by KhangMBui** [WSU-Software-Development-Club/best-by-notification#1]
Define a model in Flask named "Product" with 3 attributes: id (Integer, Primary Key), name (String), and expiration_date (Date).

**Comment by KhangMBui** [comment]
Hint:
* To define a model, create a class, name it Product, and pass "db.Model" into the parameter.
* Use db.Column to create the 3 attributes. 
* Make sure to set 'id' as the primary key.
* Ensure 'name' and 'expiration_date' cannot be null.
* Ensure 'expiration_date' is typed Date.

**Comment by mrthomaslibrary** [comment]
Issue has been completed and can be closed
