### ISSUE TITLE
Make the navigation bar in figma

### ISSUE THREAD

**Issue by KhangMBui** [WSU-Software-Development-Club/best-by-notification#2]
Follow the instruction in this video: https://www.youtube.com/watch?v=etwoLRVGt6E&t=53s&pp=ygUjbWFrZSBhIG5hdmlnYXRpb24gbWVudSBiYXIgaW4gZmlnbWE%3D

To make a navigation bar component in our Figma file: https://www.figma.com/design/IUoHWpJF2ijF5RwJfTbGuC/Best-By-Notification?node-id=0-1&node-type=canvas&t=ovrLSoxD5o1C72tc-0

**Comment by liu-petter** [comment]
Hi Khang,

Could you add me as one of the collaborators on Figma so that I could get started on the nav bar.

Thanks,
Peter

**Comment by liu-petter** [comment]
oops

**Comment by KhangMBui** [comment]
Peter,

For sure! Thank you for picking up this task!

**Comment by liu-petter** [comment]
Navigation Bar should be done, lmk if changes are needed.

**Comment by KhangMBui** [comment]
Great work, Peter! You really nailed it!

Now that you know how to create and edit a nav bar component, can you adjust the nav bar you made so that it fits our project better?

I would say make it a bit slimmer vertically and choose a different color scheme that goes well with the home page I made.

I see that we currently have 3 items: Profile, Scan, and List. Can you please add another one, "Setting," if possible?

See the below picture for reference. 

![image](https://github.com/user-attachments/assets/2a880ff2-3373-478d-aa77-9269a51f2638)

Also, it'd be greatly appreciated if you can include a screenshot of your finished work in your comment when you're done!

**Comment by liu-petter** [comment]
Thanks for the feedback!

Here's the updated version for the nav bar.

![image](https://github.com/user-attachments/assets/d48c3849-e6c8-4d35-9c6b-d35d586ff3f1)

**Comment by KhangMBui** [comment]
Great work, Peter! I don't think our app would have a user authorization system (login, logout), so I'm not sure if Profile is needed. But let's figure it out later. For now, this is good!
